In [1]:
# yeah well I am not downloading CUDA enabled torch 
# it's a freaking 2.5GB download lol

import torch

print(f"Is CUDA available? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    
print(torch.__version__)

Is CUDA available? True
GPU Name: Tesla T4
2.10.0+cu128


# Tensors

Any arrays can be called tensors (they have a more sophisticated defn but let's go with this for now).

- Tensor Dimension: directions the tensor spans.
- 0D tensor: scalar (single number)
- 1D tensor: vector (list of numbers)
- 2D tensor: matrix (table of numbers)
- 3D tensor: cube of numbers (e.g. RGB image)
- nD tensor: tensor with n dimensions (e.g. video with frames, height, width, color channels)

## Why Tensors?
- efficient mathematical operations
- efficient gpu computations, optimized for HW accelerations and parallelization
- real world data is often represented as tensors




# Creating a Tensor

In [3]:
# using empty

a = torch.empty(2, 3) # makes a 2x3 matrix. allocates memory but doesn't allcate any values. quite like C arrays!

type(a)

torch.Tensor

In [7]:
# create a tensor of zeros and ones

b = torch.zeros(2, 3)
c = torch.ones(2, 3)

print(b, c)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# random tensors

d = torch.rand(2, 3)

print(d)

# to always generate a same random tensor, we can set the random seed

torch.manual_seed(330)
e = torch.rand(2, 3)

print(e)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.9201, 0.3220, 0.0499],
        [0.4831, 0.9513, 0.1771]])


In [36]:
# custom tensor

f = torch.tensor([[1, 2, 3], [4, 5, 6]])

# you can pass any form of python iterable to the tensor constructor

g = torch.arange(0, 10, 2) # start, end, step

print(g)

h = torch.linspace(0, 10, steps=10) # start, end, number of steps

print(h)

i = torch.eye(5) # identity matrix of size 5x5

print(i)

j = torch.full((2, 3), 7) # creates a 2x3 matrix filled with the value 7

print(j)

k = torch.empty_like(j) # creates an empty tensor with the same shape and dtype as j
# remember that this doesn't allocate any values.
print(k)


# torch.rand_like() doesn't work!!

# we have to specify dtype 



tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[216415,      7,      7],
        [     7,      7,      7]])


**Important: look at the data type of the tensor. By default, PyTorch creates tensors with `float32` data type. You can specify the data type when creating a tensor using the `dtype` argument. For example, to create a tensor of integers, you can use `dtype=torch.int32`.**

Moreover, we can use `torch.to()` to change the data type of an existing tensor. For example, if you have a tensor `a` and you want to convert it to integers, you can do `a = a.to(torch.int32)`.