In [1]:
# yeah well I am not downloading CUDA enabled torch 
# it's a freaking 2.5GB download lol

import torch

print(f"Is CUDA available? {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    
print(torch.__version__)

Is CUDA available? True
GPU Name: Tesla T4
2.10.0+cu128


# Tensors

Any arrays can be called tensors (they have a more sophisticated defn but let's go with this for now).

- Tensor Dimension: directions the tensor spans.
- 0D tensor: scalar (single number)
- 1D tensor: vector (list of numbers)
- 2D tensor: matrix (table of numbers)
- 3D tensor: cube of numbers (e.g. RGB image)
- nD tensor: tensor with n dimensions (e.g. video with frames, height, width, color channels)

## Why Tensors?
- efficient mathematical operations
- efficient gpu computations, optimized for HW accelerations and parallelization
- real world data is often represented as tensors




# Creating a Tensor

In [3]:
# using empty

a = torch.empty(2, 3) # makes a 2x3 matrix. allocates memory but doesn't allcate any values. quite like C arrays!

type(a)

torch.Tensor

In [7]:
# create a tensor of zeros and ones

b = torch.zeros(2, 3)
c = torch.ones(2, 3)

print(b, c)

tensor([[0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [19]:
# random tensors

d = torch.rand(2, 3)

print(d)

# to always generate a same random tensor, we can set the random seed

torch.manual_seed(330)
e = torch.rand(2, 3)

print(e)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])
tensor([[0.9201, 0.3220, 0.0499],
        [0.4831, 0.9513, 0.1771]])


In [36]:
# custom tensor

f = torch.tensor([[1, 2, 3], [4, 5, 6]])

# you can pass any form of python iterable to the tensor constructor

g = torch.arange(0, 10, 2) # start, end, step

print(g)

h = torch.linspace(0, 10, steps=10) # start, end, number of steps

print(h)

i = torch.eye(5) # identity matrix of size 5x5

print(i)

j = torch.full((2, 3), 7) # creates a 2x3 matrix filled with the value 7

print(j)

k = torch.empty_like(j) # creates an empty tensor with the same shape and dtype as j
# remember that this doesn't allocate any values.
print(k)


# torch.rand_like() doesn't work!!

# we have to specify dtype 



tensor([0, 2, 4, 6, 8])
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([[7, 7, 7],
        [7, 7, 7]])
tensor([[216415,      7,      7],
        [     7,      7,      7]])


**Important: look at the data type of the tensor. By default, PyTorch creates tensors with `float32` data type. You can specify the data type when creating a tensor using the `dtype` argument. For example, to create a tensor of integers, you can use `dtype=torch.int32`.**

Moreover, we can use `torch.to()` to change the data type of an existing tensor. For example, if you have a tensor `a` and you want to convert it to integers, you can do `a = a.to(torch.int32)`.

In [38]:
l = torch.rand_like(j, dtype=torch.float32)

print(l)

tensor([[0.5888, 0.8448, 0.1381],
        [0.3309, 0.5760, 0.7445]])


# Operations on Tensors

In [40]:
ten = torch.rand(2, 3)

print("ten:", ten)

ten: tensor([[0.9381, 0.6348, 0.7307],
        [0.6875, 0.8619, 0.6447]])


In [61]:
# integer ops

# addition

print(f"ten + 2: {ten + 2}")

# deletion

print(f"ten - 2: {ten - 2}")

# multiplication

print(f"ten * 2: {ten * 2}")

# division

print(f"ten / 2: {ten / 2}")

# mod

print(f"ten * 20: {ten * 20}")
print(f"(ten * 20) % 2: {(ten * 20) % 2}")

# abs

print(f"abs(ten * 20): {torch.abs(ten- 2)}")



ten + 2: tensor([[2.9381, 2.6348, 2.7307],
        [2.6875, 2.8619, 2.6447]])
ten - 2: tensor([[-1.0619, -1.3652, -1.2693],
        [-1.3125, -1.1381, -1.3553]])
ten * 2: tensor([[1.8761, 1.2697, 1.4615],
        [1.3751, 1.7237, 1.2894]])
ten / 2: tensor([[0.4690, 0.3174, 0.3654],
        [0.3438, 0.4309, 0.3223]])
ten * 20: tensor([[18.7613, 12.6968, 14.6145],
        [13.7509, 17.2374, 12.8936]])
(ten * 20) % 2: tensor([[0.7613, 0.6968, 0.6145],
        [1.7509, 1.2374, 0.8936]])
abs(ten * 20): tensor([[1.0619, 1.3652, 1.2693],
        [1.3125, 1.1381, 1.3553]])


In [73]:
# tensor ops

torch.manual_seed(10101)
a1 = torch.rand(2, 3) * 100
a2 = torch.rand(2, 3) * 100

print(a1)
print(a2)

# element-wise addition

print(f"\na1 + a2: {a1 + a2}")

# element-wise subtraction

print(f"\na1 - a2: {a1 - a2}")

# element-wise multiplication

print(f"\na1 * a2: {a1 * a2}")

# element-wise division [integer division also possible via ``//``]

print(f"\na1 / a2: {a1 / a2}")

# floor, ceil, round also available

# clamping

print(f"\na1 clamped between 20 and 80: {torch.clamp(a1, min=20, max=80)}")


tensor([[98.6526, 59.7209, 87.7269],
        [31.8950, 57.4184, 77.8326]])
tensor([[39.3213, 25.3042, 63.2083],
        [48.5318, 73.8185, 63.4072]])

a1 + a2: tensor([[137.9739,  85.0251, 150.9352],
        [ 80.4268, 131.2369, 141.2397]])

a1 - a2: tensor([[ 59.3314,  34.4168,  24.5186],
        [-16.6368, -16.4001,  14.4254]])

a1 * a2: tensor([[3879.1497, 1511.1881, 5545.0688],
        [1547.9238, 4238.5396, 4935.1431]])

a1 / a2: tensor([[2.5089, 2.3601, 1.3879],
        [0.6572, 0.7778, 1.2275]])

a1 clamped between 20 and 80: tensor([[80.0000, 59.7209, 80.0000],
        [31.8950, 57.4184, 77.8326]])


In [91]:
# stuff inside torch entries

b1 = torch.randint(size=(2,3),  low=80, high=100)

print(b1)


print("tensor sum:", torch.sum(b1))
print(f"column sum: {torch.sum(b1, dim=0)}")
print(f"row sum: {torch.sum(b1, dim=1)}")

print("")

# torch.mean() --> must be float tensor
# we can pass `dim=` to specify the dimension along which to compute the mean too!

print(f"tensor max: {torch.max(b1)}")
print(f"column max: {torch.max(b1, dim=0)}")
print(f"row max: {torch.max(b1, dim=1)}")

# notice how the row and column max functions return the indices where the max value was found as well.
# useful thing!

# for global location of max value, we can use torch.argmax()
print(f"\nglobal max value: {torch.max(b1)}")
print(f"global max index: {torch.argmax(b1)}")

# for min, we use torch.min() and torch.argmin()
print(f"\nglobal min value: {torch.min(b1)}")
print(f"global min index: {torch.argmin(b1)}")


tensor([[95, 83, 88],
        [89, 90, 92]])
tensor sum: tensor(537)
column sum: tensor([184, 173, 180])
row sum: tensor([266, 271])

tensor max: 95
column max: torch.return_types.max(
values=tensor([95, 90, 92]),
indices=tensor([0, 1, 1]))
row max: torch.return_types.max(
values=tensor([95, 92]),
indices=tensor([0, 2]))

global max value: 95
global max index: 0

global min value: 83
global min index: 1


## Matrix operations for tensors

- `torch.matmul()` is used for matrix multiplication, while `torch.mm()` is used for matrix multiplication of 2D tensors. The main difference is that `torch.matmul()` can handle tensors of higher dimensions (e.g., 3D or more) and will perform the appropriate matrix multiplication based on the dimensions of the input tensors, while `torch.mm()` is specifically designed for 2D tensors and will raise an error if the input tensors are not 2D. Meanwhile `torch.bmm()` is used for batch matrix multiplication, which allows you to perform matrix multiplication on batches of matrices. It takes two 3D tensors as input, where the first dimension represents the batch size, and performs matrix multiplication on each pair of matrices in the batch.

- `torch.transspose()`, `torch.det()`, `torch.inverse()`, `torch.eig()`, `torch.svd()`, `torch.qr()` available!


- `torch.dot()` is used for dot product of 1D tensors (vectors), while `torch.cross()` is used for cross product of 3D vectors. The main difference is that `torch.dot()` computes the sum of the products of the corresponding elements of two vectors, resulting in a scalar value, while `torch.cross()` computes the cross product of two 3D vectors, resulting in a new vector that is perpendicular to both input vectors.

    Note that we must specify the dimension along which to perform the cross product when using `torch.cross()`, as it can operate on tensors of higher dimensions. For example, if we have two 2D tensors `a1` and `a2`, we can compute their cross product along the second dimension (rows) using `torch.cross(a1, a2, dim=1)`.

In [ ]:
# raises an error since we CANNOT dot product 2D tensors using torch.dot()
# print(f"a1 dot a2: {torch.dot(a1, a2)}")

# flatten() -> flattens the tensor to 1D

# so, tensor([[98.6526, 59.7209, 87.7269],
#            [31.8950, 57.4184, 77.8326]])
# is reduced to tensor([98.6526, 59.7209, 87.7269, 31.8950, 57.4184, 77.8326])

print(f"a1 dot a2: {torch.dot(a1.flatten(), a2.flatten())}")

# `reshape()` can also be used to flatten the tensor
# but it creates a new tensor. 

a1 dot a2: 21657.013671875


In [ ]:
# raises an error since we cannot cross 2D vectors using torch.cross()

# print("a1 cross a2: ", torch.cross(a1, a2, dim=0)) # cross product along the first dimension (columns)

# this is perfect

print("a1 cross a2: ", torch.cross(a1, a2, dim=1)) # cross product along the second dimension (rows)

a1 cross a2:  tensor([[ 1555.0037, -2786.1328,   148.0185],
        [-2104.7439,  1754.9841,  -432.1782]])


### Comparison ops 

- when we do a comparison op, we get a tensor of boolean values (True/False) in the o/p tensor

- `<`, `>`, `==`, `!=`, `<=`, `>=` etc are available as operators. functions: `torch.eq()`, `torch.ne()`, `torch.gt()`, `torch.lt()`, `torch.ge()`, `torch.le()`.

### Other mathematical operations

- `torch.log()`, `torch.exp()`, `torch.sqrt()`, `torch.sin()`, `torch.cos()`, `torch.tan()` etc.

# Inplace ops

- when we do a entry by entry op, we always get a new tensor as o/p. this will hog a lot of memory for super large tensors

- say we have two tensors `a` and `b`, and we want to add them together. If we do `c = a + b`, we get a new tensor `c` that contains the result of the addition. However, if we want to perform the addition in place (i.e., modify `a` directly), we can use the `add_()` method: `a.add_(b)`. This will add `b` to `a` and store the result back in `a`, without creating a new tensor.

- other functions: `sub_()`, `mul_()`, `div_()`, `pow_()`, `sqrt_()`, `log_()`, `exp_()`, `relu_()` etc.

- basically underscore at the end of operation name, and make that an inplace operation! :3

### Copying tensors

- simply doing `a = b` just assigns the memory address of `b` to `a`, so when we modify `b`, `a` is also modified.
- to create an actual copy of the tensor, we can use the `clone()` method: `a = b.clone()`. This creates a new tensor with the same values as `b`, but with a different memory address.



--- 

Up till now, all operations have been done on the CPU. If we need the GPU, we need to change the device.

In [ ]:
print(torch.cuda.is_available())

device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

print(device)

# now when we create a new tensor, we need to specify the device with `device=device`

a_gpu = torch.rand(2, 3, device=device)

print(a_gpu)

# migrate a CPU tensor to GPU

a_gpu2 = a1.to(device)

print(a_gpu2)

True
cuda
tensor([[0.0751, 0.4367, 0.7857],
        [0.0076, 0.3611, 0.7149]], device='cuda:0')
tensor([[98.6526, 59.7209, 87.7269],
        [31.8950, 57.4184, 77.8326]], device='cuda:0')
